export const userActionTypes = {
  USER_LOGIN_USER_REQUEST: 'USER_LOGIN_USER_REQUEST',
  USER_LOGIN_USER_SUCCESS: 'USER_LOGIN_USER_SUCCESS',
  USER_LOGIN_USER_FAILURE: 'USER_LOGIN_USER_FAILURE',
  USER_REGISTER_USER_REQUEST: 'USER_REGISTER_USER_REQUEST',
  USER_REGISTER_USER_SUCCESS: 'USER_REGISTER_USER_SUCCESS',
  USER_REGISTER_USER_FAILURE: 'USER_REGISTER_USER_FAILURE',
  USER_FETCH_USER_INFO_FROM_TOKEN: 'USER_FETCH_USER_INFO_FROM_TOKEN',
  USER_CLEAR_USER_STATE: 'USER_CLEAR_USER_STATE',
};
